version: "3"

services:
  webapp:
    build: .
    
    expose:
      - "8080"
    environment:
      - C9_HOSTNAME=https://www.csud-reservation.com
      - C9_IP=0.0.0.0
      - C9_PORT=8080
      - VIRTUAL_HOST=www.csud-reservation.com
      - LETSENCRYPT_HOST=www.csud-reservation.com
      - LETSENCRYPT_EMAIL=csud-reservation@gmail.com

    network_mode: "bridge"

  nginx-proxy:
      restart: always
      image: jwilder/nginx-proxy
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - /srv/docker/nginx/certs:/etc/nginx/certs:ro
          - /etc/nginx/vhost.d
          - /usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion
      volumes:
          - /srv/docker/nginx/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock
      volumes_from:
          - nginx-proxy