version: '3'
services:
version: "3"

services:
  web:
    build: .
    ports:
      - 8000:8080
    expose:
      - 8080
    environment:
      - C9_HOSTNAME=https://www.csud-reservation.com
      - C9_IP=0.0.0.0
      - C9_PORT=8080
      - VIRTUAL_HOST=www.csud-reservation.com
      - LETSENCRYPT_HOST=www.csud-reservation.com
      - LETSENCRYPT_EMAIL=csud-reservation@gmail.com