version: "3.2"

services:
  web:
    ports:
      - "5000:8080"
    volumes:
      - type: volume
        source: sqlite-data
        target: /sqlite-data
        volume:
          nocopy: true
    environment:
      - DEV_DATABASE_URL=sqlite:////sqlite-data/data.sqlite
      - FLASK_CONFIG=development
      - C9_HOSTNAME=https://beta-version.csud-reservation.com
      - VIRTUAL_HOST=beta-version.csud-reservation.com
      - LETSENCRYPT_HOST=beta-version.csud-reservation.com

  backup:
    restart: always
    build: ./backup
    env-file:
      - backup/aws.env

    volumes:
      - type: volume
        source: sqlite-data
        target: /sqlite-data
        volume:
          nocopy: true


volumes:
  sqlite-data:
