version: "3.2"

services:
  web:
    restart: always
    build: .
    
    expose:
      - "8080"
    environment:
      - C9_IP=0.0.0.0
      - C9_PORT=8080
      - LETSENCRYPT_EMAIL=21-learning@gmail.com

    network_mode: "bridge"

  backup:
    restart: always
    build: ./backup

  