version: "3.2"

services:
  web:
    ports:
      - "5000:8080"
    volumes:
      - type: volume
        source: sqlite-data
        target: /sqlite-data
        volume:
          nocopy: true
    environment:
      - DEV_DATABASE_URL=sqlite:////sqlite-data/data.sqlite
      - FLASK_CONFIG=development

volumes:
  sqlite-data:

