version: "3.2"

services:
  web:
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: sqlite-data
        target: /sqlite-data
        volume:
          nocopy: true
    env_file: host.env
    environment:
      DEV_DATABASE_URL: sqlite:////sqlite-data/data.sqlite
      FLASK_CONFIG: development

  backup:
    restart: always
    build:
      context: ./backup
      args:  
        - version=2017-production

    volumes:
      - type: volume
        source: sqlite-data
        target: /sqlite-data
        volume:
          nocopy: true


volumes:
  sqlite-data:
