version: '3'
services:
version: "3"

services:
  web:
    build: .
    ports:
      - 8000:8080
    expose:
      - 8080
    environment:
      - C9_HOSTNAME=https://${HOST}
      - C9_IP=0.0.0.0
      - C9_PORT=8080
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=21-learning@gmail.com