#!/usr/bin/env python
import os
from app import create_app, db
from app.models import User, Role, Reservation, Room, Timeslot, Weekday, reservations_users, reservations_timeslots
from flask_script import Manager, Shell, Server
from flask_migrate import Migrate, MigrateCommand

# génération schéma relationnel
import sadisplay

# interface d'administration
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

from data.sigles import sigles
from data.timeslots import timeslots
from data.utils import extract_sigles, extract_timeslots, extract_rooms

app = create_app(os.getenv('FLASK_CONFIG') or 'default')
manager = Manager(app)
migrate = Migrate(app, db)

# initialisation de Admin
admin = Admin(app, name='CSUD Réservation : admin', template_mode='bootstrap3')

models = [User, Role, Reservation, Room, Timeslot, Weekday]
for model in models:
    admin.add_view(ModelView(model, db.session))


def make_shell_context():
    return dict(app=app, db=db,
        User=User,
        Role=Role,
        Reservation=Reservation,
        Room=Room,
        Timeslot=Timeslot,
        Weekday=Weekday
    )
    

if os.getenv('C9_HOSTNAME'):
    manager.add_command("runserver", Server(
        host=os.getenv('C9_IP'),
        port=os.getenv('C9_PORT')
    ))
    print("App started on Cloud9, available on", 'https://' + os.getenv('C9_HOSTNAME'))


manager.add_command("shell", Shell(make_context=make_shell_context, use_ipython=True))
manager.add_command('db', MigrateCommand)

tmp_timetable_txt = "data/timetable.txt"
tmp_rooms_txt = "data/rooms.txt"
@manager.command
def txt(input_pdf, out_txt):
    try:
        from sh import pdf2txt, rm
    except:
        print("impossible d'exécuter la commande pdf2txt nécessaire à la conversion du fichier. Installer d'abord le package python pdf miner avec sudo apt-get install python-pdfminer")
        
    pdf2txt(input_pdf, _out = out_txt)


    
    
@manager.command
def initdb():
    db.drop_all()
    db.create_all()
    
    timeslots = extract_timeslots()
    rooms = extract_rooms()
    sigles = extract_sigles()
    
    # auto data loading from different datasources
    Timeslot.insert_timeslots(timeslots)
    Weekday.insert_days()
    Role.insert_roles()
    User.insert_admin()
    User.insert_teachers(sigles)
    Room.insert_rooms(rooms)
    
    
@manager.command
def erd():
    ''' outputs entity relationship diagram into erd.png '''
    try:
        from sh import eralchemy
        eralchemy('-i', app.config['SQLALCHEMY_DATABASE_URI'], '-o', 'erd.png')
        from sh import c9
        c9('erd.png')
    except ImportError as e:
        print(str(e))  
        

@manager.command
def rel():
    ''' outputs relational diagram into rel.png '''
    try:
        from sh import dot
        desc = sadisplay.describe([
            User,
            Role,
            Reservation,
            Room,
            Timeslot,
            Weekday,
            reservations_users,
            reservations_timeslots
        ])
        with open('schema.dot', 'w', encoding='utf-8') as f:
            f.write(sadisplay.dot(desc))
            
        dot("-Tpng", "schema.dot", "-o", "rel.png")
        dot("-Tpdf", "schema.dot", "-o", "rel.pdf")
        dot("-Tsvg", "schema.dot", "-o", "rel.svg")

    except ImportError as e:
        print(str(e))

@manager.command
def sqldump():
    from sqlalchemy import create_engine
    from sqlalchemy.schema import CreateTable
    
    models = [User, Role, Reservation, Room, Timeslot, Weekday]
    association_tables = [reservations_users, reservations_timeslots]

    sql_url = app.config['SQLALCHEMY_DATABASE_URI']
    db_engine = create_engine(sql_url)
    
    with open('data-dev-ddl.sql', 'w') as fd:
        for model in models:
            sql_ddl = CreateTable(model.__table__).compile(db_engine)
            sql_ddl = str(sql_ddl).strip()
            fd.write(str(sql_ddl)  + ';\n\n')
        for table in association_tables:
            sql_ddl = CreateTable(table).compile(db_engine)
            sql_ddl = str(sql_ddl).strip()
            fd.write(str(sql_ddl)  + ';\n\n')
            
    try:
        from sh import c9
        c9('data-dev-ddl.sql')
    except:
        pass
    

@manager.command
def clean():
    files = [
        'rel.*',
        'schema.*'
    ]
    
    from sh import rm
            
    for file in files:
        rm("-f", file)
    

@manager.command
def loadedt():
    """ Loads data from CSV file generated by EDT (Emploi Du Temps) """
    
    # 

@manager.command
def test():
    """Run the unit tests."""
    import unittest
    tests = unittest.TestLoader().discover('tests')
    unittest.TextTestRunner(verbosity=2).run(tests)



if __name__ == '__main__':
    manager.run()
