#!/usr/bin/env python
import os
from app import create_app, db
from app.models import init_weekdays, User, Role, StudentGroup, Reservation, Room, Timeslot, Weekday
from flask_script import Manager, Shell
from flask_migrate import Migrate, MigrateCommand

app = create_app(os.getenv('FLASK_CONFIG') or 'default')
manager = Manager(app)
migrate = Migrate(app, db)


def make_shell_context():
    return dict(app=app, db=db,
        User=User,
        Role=Role,
        StudentGroup=StudentGroup,
        Reservation=Reservation,
        Room=Room,
        Timeslot=Timeslot,
        Weekday=Weekday
    )
    
manager.add_command("shell", Shell(make_context=make_shell_context, use_ipython=True))
manager.add_command('db', MigrateCommand)

@manager.command
def init_db():
    db.drop_all()
    db.create_all()
    init_weekdays()
    

@manager.command
def loadedt():
    """ Loads data from CSV file generated by EDT (Emploi Du Temps) """
    pass

@manager.command
def test():
    """Run the unit tests."""
    import unittest
    tests = unittest.TestLoader().discover('tests')
    unittest.TextTestRunner(verbosity=2).run(tests)


if __name__ == '__main__':
    manager.run()
